import { Project, Service, Testimonial, MetricItem, NavItem } from "@/types";

export const personalInfo = {
  name: "Tushar Faruk",
  title: "Brand Designer",
  greeting: "HELLO, I'M",
  tagline: "I Craft Iconic Brands & Visual Systems That Stand Out.",
  bio: "I'm a Brand & Visual Identity Designer helping startups and global businesses build memorable, high-impact brand systems and visual experiences.",
  avatar: "https://lh3.googleusercontent.com/d/1T2VLGzKpGfz_CnPHwozeY77I0EbvTeaA",
  heroPortrait: "https://lh3.googleusercontent.com/d/1T2VLGzKpGfz_CnPHwozeY77I0EbvTeaA",
  introVideoUrl: "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ?autoplay=1",
  experienceYears: "5+",
  email: "tusharfaruk@gmail.com",
  phone: "+880 1700 000000",
  location: "Dhaka, Bangladesh / Remote Worldwide",
  cvUrl: "/cv/Tushar_Faruk_CV.pdf",
  socials: {
    dribbble: "https://dribbble.com",
    behance: "https://behance.net",
    linkedin: "https://linkedin.com",
    github: "https://github.com",
  },
};

export const navItems: NavItem[] = [
  { label: "Home", href: "/#home", iconName: "Home" },
  { label: "About", href: "/#about", iconName: "User" },
  { label: "Services", href: "/#services", iconName: "Briefcase" },
  { label: "Portfolio", href: "/#portfolio", iconName: "Folder" },
  { label: "Skills", href: "/#skills", iconName: "Code" },
  { label: "Blog", href: "/#blog", iconName: "FileText" },
  { label: "Contact", href: "/#contact", iconName: "Mail" },
];

export const trustedClients = [
  { name: "Google", logoText: "Google" },
  { name: "Microsoft", logoText: "Microsoft" },
  { name: "airbnb", logoText: "airbnb" },
  { name: "Slack", logoText: "slack" },
  { name: "Dropbox", logoText: "Dropbox" },
];

export const fallbackServices: Service[] = [
  {
    _id: "srv-1",
    title: "Brand Identity & Strategy",
    description: "Developing comprehensive visual identities, logos, and positioning that give brands a powerful voice.",
    icon: "Sparkles",
    badgeColor: "purple",
    linkText: "Explore Branding →",
    order: 1,
  },
  {
    _id: "srv-2",
    title: "Logo & Visual Systems",
    description: "Creating timeless logos, iconography sets, custom typography, and dynamic visual language guidelines.",
    icon: "Rocket",
    badgeColor: "blue",
    linkText: "View Logo Work →",
    order: 2,
  },
  {
    _id: "srv-3",
    title: "Packaging & Print Design",
    description: "Designing tactile luxury product packaging, stationery systems, and marketing collateral.",
    icon: "Smartphone",
    badgeColor: "purple",
    linkText: "See Packaging →",
    order: 3,
  },
  {
    _id: "srv-4",
    title: "Design Systems & Digital UI",
    description: "Bridging brand aesthetics into digital products with scalable Figma UI design systems and web experiences.",
    icon: "Code",
    badgeColor: "blue",
    linkText: "Learn More →",
    order: 4,
  },
];

export const fallbackProjects: Project[] = [
  {
    _id: "lumina-brand-identity",
    slug: "lumina-brand-identity",
    title: "Lumina Brand Identity",
    category: "Brand Identity",
    subtitle: "Visual Identity & Guidelines",
    image: "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?q=80&w=1200&auto=format&fit=crop",
    overview: "A sleek, modernist visual identity system created for an architectural lighting design studio based in London.",
    challenge: "The client needed an elevated identity reflecting both minimalist luxury and technological innovation.",
    solution: "Developed a custom geometric wordmark, dynamic lighting gradient palettes, and complete brand stationery suite.",
    client: "Lumina Lighting Studio",
    duration: "6 Weeks",
    role: "Lead Brand Designer",
    tools: ["Adobe Illustrator", "Adobe Photoshop", "Figma", "InDesign"],
    technologies: ["Illustrator", "Photoshop", "Print Production"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542744094-3a31f272c490?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 1,
  },
  {
    _id: "aura-coffee-roasters",
    slug: "aura-coffee-roasters",
    title: "Aura Coffee Roasters",
    category: "Packaging Design",
    subtitle: "Brand & Sustainable Packaging",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=1200&auto=format&fit=crop",
    overview: "Artisanal coffee packaging, typography, and visual branding celebrating ethical sourcing and rich botanical flavors.",
    challenge: "Standing out on crowded specialty coffee shelves while communicating single-origin roast profiles clearly.",
    solution: "Designed custom color-coded roast labels, embossed foil packaging bags, and illustrated topographic origin maps.",
    client: "Aura Roastery Co.",
    duration: "4 Weeks",
    role: "Packaging & Brand Designer",
    tools: ["Adobe Illustrator", "Adobe Photoshop", "Dimension 3D"],
    technologies: ["Illustrator", "Photoshop"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 2,
  },
  {
    _id: "nexus-tech-rebrand",
    slug: "nexus-tech-rebrand",
    title: "Nexus Tech Rebrand",
    category: "Logo Design",
    subtitle: "Logo System & Visual Assets",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop",
    overview: "A future-forward rebrand for an enterprise AI cloud infrastructure provider.",
    challenge: "Modernizing a decade-old legacy brand into a clean, nimble identity suitable for global tech conferences and web.",
    solution: "Crafted a multi-dimensional monogram logo, cohesive icon library, and comprehensive 60-page brand guidelines.",
    client: "Nexus Cloud Systems",
    duration: "8 Weeks",
    role: "Brand Identity Lead",
    tools: ["Adobe Illustrator", "Adobe Photoshop", "Figma"],
    technologies: ["Illustrator", "Photoshop", "Brand System"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 3,
  },
  {
    _id: "solis-skincare-identity",
    slug: "solis-skincare-identity",
    title: "Solis Organic Skincare",
    category: "Brand Identity",
    subtitle: "Luxury Cosmetics & Packaging",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1200&auto=format&fit=crop",
    overview: "Holistic luxury skincare branding designed with gentle earth tones, bespoke serif typography, and tactile glass bottles.",
    challenge: "Creating an authentic premium aesthetic that emphasizes organic purity and high dermatologist standards.",
    solution: "Curated an organic color palette, custom minimalist bottle typography, and textured unboxing packaging.",
    client: "Solis Botanicals",
    duration: "5 Weeks",
    role: "Brand & Packaging Designer",
    tools: ["Adobe Illustrator", "Adobe Photoshop", "Blender"],
    technologies: ["Illustrator", "Photoshop"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 4,
  },
  {
    _id: "vortex-energy-drinks",
    slug: "vortex-energy-drinks",
    title: "Vortex Energy Can Design",
    category: "Packaging Design",
    subtitle: "Can Graphics & Campaign Art",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=1200&auto=format&fit=crop",
    overview: "High-octane beverage can design featuring neon ultraviolet line art and metallic textures.",
    challenge: "Attracting Gen-Z esports athletes and creators with bold shelf presence.",
    solution: "Created dynamic isometric typography, metallic ink separations, and matching promotional billboards.",
    client: "Vortex Beverages",
    duration: "3 Weeks",
    role: "Creative Packaging Specialist",
    tools: ["Adobe Illustrator", "Adobe Photoshop"],
    technologies: ["Illustrator", "Photoshop"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1527661591475-527312dd65f5?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 5,
  },
  {
    _id: "hyperion-fintech-brand",
    slug: "hyperion-fintech-brand",
    title: "Hyperion Digital Bank",
    category: "Brand Identity",
    subtitle: "FinTech Brand System & App UI",
    image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1200&auto=format&fit=crop",
    overview: "Comprehensive visual identity and metal debit card design for a next-generation borderless digital banking app.",
    challenge: "Establishing trust, security, and prestige in a competitive neobank market.",
    solution: "Designed a laser-etched black titanium card, custom cybernetic monogram, and consistent digital brand guidelines.",
    client: "Hyperion Capital",
    duration: "7 Weeks",
    role: "Brand & Visual System Lead",
    tools: ["Adobe Illustrator", "Figma", "Adobe Photoshop"],
    technologies: ["Illustrator", "Photoshop", "Figma"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 6,
  },
  {
    _id: "zenith-apparel-lookbook",
    slug: "zenith-apparel-lookbook",
    title: "Zenith Apparel Studio",
    category: "Brand Identity",
    subtitle: "Streetwear Brand & Lookbook",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1200&auto=format&fit=crop",
    overview: "Minimalist brutalist brand identity and editorial lookbook publication for an independent streetwear collective.",
    challenge: "Creating an authentic underground fashion aesthetic with high-end print finishes.",
    solution: "Crafted custom heavyweight hangtags, typography posters, woven labels, and digital lookbook layouts.",
    client: "Zenith Studio",
    duration: "4 Weeks",
    role: "Art Director & Brand Designer",
    tools: ["Adobe Photoshop", "Adobe InDesign", "Adobe Illustrator"],
    technologies: ["Photoshop", "Illustrator"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 7,
  },
  {
    _id: "kura-japanese-matcha",
    slug: "kura-japanese-matcha",
    title: "Kura Ceremonial Matcha",
    category: "Packaging Design",
    subtitle: "Ceremonial Tea Tin & Identity",
    image: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=1200&auto=format&fit=crop",
    overview: "Authentic Kyoto matcha tin packaging blending Japanese calligraphy with Scandinavian minimalism.",
    challenge: "Balancing heritage cultural elements with clean modern aesthetics for international consumers.",
    solution: "Created custom ink-brush kanji vector marks, matte washi paper labels, and embossed gold foil seals.",
    client: "Kura Tea Co.",
    duration: "5 Weeks",
    role: "Brand & Packaging Designer",
    tools: ["Adobe Illustrator", "Adobe Photoshop"],
    technologies: ["Illustrator", "Photoshop"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 8,
  },
  {
    _id: "nova-cybersecurity-mark",
    slug: "nova-cybersecurity-mark",
    title: "Nova Defense Systems",
    category: "Logo Design",
    subtitle: "Security Iconography & Brand",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1200&auto=format&fit=crop",
    overview: "Geometric emblem and branding for an automated zero-trust cloud security platform.",
    challenge: "Designing a memorable badge that symbolizes an impenetrable cryptographic shield.",
    solution: "Synthesized precision geometry with glowing gradient accents, creating scalable icons for web and software consoles.",
    client: "Nova Security Labs",
    duration: "4 Weeks",
    role: "Logo & Icon Designer",
    tools: ["Adobe Illustrator", "Adobe Photoshop"],
    technologies: ["Illustrator", "Photoshop"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 9,
  },
  {
    _id: "prism-creative-agency",
    slug: "prism-creative-agency",
    title: "Prism Collective Agency",
    category: "Brand Identity",
    subtitle: "Visual Identity & Motion Graphics",
    image: "https://images.unsplash.com/photo-1558655146-d09347e92766?q=80&w=1200&auto=format&fit=crop",
    overview: "Dynamic visual identity system centered around optical chromatic aberration and kinetic typography.",
    challenge: "Reflecting a multidisciplinary creative studio that produces film, 3D, and digital experiences.",
    solution: "Engineered generative color shifts, responsive grid rules, and modular business card suites.",
    client: "Prism Creative Group",
    duration: "6 Weeks",
    role: "Lead Brand Identity Designer",
    tools: ["Adobe Illustrator", "Adobe Photoshop", "After Effects"],
    technologies: ["Illustrator", "Photoshop"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1558655146-d09347e92766?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542744094-24638eff58bb?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 10,
  },
  {
    _id: "ember-craft-brewery",
    slug: "ember-craft-brewery",
    title: "Ember Craft Beer Series",
    category: "Packaging Design",
    subtitle: "Label Art & Custom Typography",
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?q=80&w=1200&auto=format&fit=crop",
    overview: "Illustrated craft beer labels with vintage woodcut engravings and vibrant metallic foil accents.",
    challenge: "Creating distinct visual personalities for 4 seasonal brews under a cohesive master brand.",
    solution: "Hand-crafted custom woodcut style vector illustrations and tactile embossed paper labels.",
    client: "Ember Brewing Co.",
    duration: "5 Weeks",
    role: "Illustrator & Packaging Designer",
    tools: ["Adobe Illustrator", "Adobe Photoshop"],
    technologies: ["Illustrator", "Photoshop"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1535958636474-b021ee887b13?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518176258769-f227c798150e?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 11,
  },
  {
    _id: "velocity-electric-bikes",
    slug: "velocity-electric-bikes",
    title: "Velocity Mobility Brand",
    category: "Brand Identity",
    subtitle: "Urban EV Brand & Decal System",
    image: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?q=80&w=1200&auto=format&fit=crop",
    overview: "High-performance urban mobility brand identity, bike frame graphics, and companion app design system.",
    challenge: "Conveying lightweight speed, Scandinavian engineering, and urban eco-friendliness.",
    solution: "Designed aerodynamic frame typography, sleek reflective decals, and helmet accessories branding.",
    client: "Velocity Mobility",
    duration: "6 Weeks",
    role: "Brand & Industrial Graphics Lead",
    tools: ["Adobe Illustrator", "Adobe Photoshop", "Figma"],
    technologies: ["Illustrator", "Photoshop"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 12,
  },
  {
    _id: "arcadia-perfume-identity",
    slug: "arcadia-perfume-identity",
    title: "Arcadia Parfums",
    category: "Packaging Design",
    subtitle: "Luxury Bottle & Box Packaging",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1200&auto=format&fit=crop",
    overview: "French luxury fragrance branding with custom heavy crystal bottle silhouettes and velvet unboxing chests.",
    challenge: "Creating a museum-grade collector's fragrance experience with subtle understated opulence.",
    solution: "Designed custom gold debossed crests, silk ribbon closures, and bespoke luxury fragrance typography.",
    client: "Maison Arcadia Paris",
    duration: "5 Weeks",
    role: "Luxury Packaging Art Director",
    tools: ["Adobe Photoshop", "Adobe Illustrator", "Cinema 4D"],
    technologies: ["Photoshop", "Illustrator"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547887537-6158d64c35b3?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 13,
  },
  {
    _id: "axiom-typography-system",
    slug: "axiom-typography-system",
    title: "Axiom Typeface & Specimen",
    category: "Logo Design",
    subtitle: "Custom Variable Font Family",
    image: "https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?q=80&w=1200&auto=format&fit=crop",
    overview: "A 12-weight geometric sans-serif variable typeface designed for luxury editorial publishing and interfaces.",
    challenge: "Crafting distinct letterforms with sharp ink traps that remain crisp at small caption sizes.",
    solution: "Engineered full Latin glyph sets, Cyrillic alternates, and an interactive digital specimen poster book.",
    client: "Axiom Type Foundry",
    duration: "10 Weeks",
    role: "Type Designer & Brand Artist",
    tools: ["Adobe Illustrator", "Glyphs", "Adobe InDesign"],
    technologies: ["Illustrator", "Type Design"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 14,
  },
  {
    _id: "orion-audio-brand",
    slug: "orion-audio-brand",
    title: "Orion Studio Headphones",
    category: "Brand Identity",
    subtitle: "Acoustics Brand & Product Box",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1200&auto=format&fit=crop",
    overview: "Audiophile studio monitor headphone identity with magnetic soft-touch gift packaging and laser-engraved earcups.",
    challenge: "Standing out in both professional music studios and high-end consumer retail displays.",
    solution: "Created an acoustic soundwave emblem, precision foil box sleeves, and unboxing instruction manuals.",
    client: "Orion Acoustics",
    duration: "4 Weeks",
    role: "Brand & Packaging Designer",
    tools: ["Adobe Illustrator", "Adobe Photoshop"],
    technologies: ["Illustrator", "Photoshop"],
    liveUrl: "https://behance.net",
    githubUrl: "https://github.com",
    gallery: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1400&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=1400&auto=format&fit=crop",
    ],
    featured: true,
    order: 15,
  },
];

export const metricsData: MetricItem[] = [
  {
    icon: "Smile",
    value: "80+",
    label: "Happy Clients",
  },
  {
    icon: "FolderCheck",
    value: "120+",
    label: "Projects Completed",
  },
  {
    icon: "Coffee",
    value: "5+",
    label: "Years Experience",
  },
  {
    icon: "Trophy",
    value: "15+",
    label: "Awards Received",
  },
];

export const fallbackTestimonials: Testimonial[] = [
  {
    _id: "test-1",
    clientName: "Alexander Vance",
    clientRole: "Founder & Creative Director",
    clientCompany: "Lumina Studio",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop",
    quote: "Tushar transformed our entire visual identity. His mastery of typography, color psychology, and brand storytelling is world-class.",
    rating: 5,
  },
  {
    _id: "test-2",
    clientName: "David Brown",
    clientRole: "CEO",
    clientCompany: "Nexus Cloud Systems",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
    quote: "Working with Tushar was seamless. He delivered a future-proof brand system and packaging designs that immediately elevated our market presence.",
    rating: 5,
  },
  {
    _id: "test-3",
    clientName: "Elena Rostova",
    clientRole: "Brand Marketing Lead",
    clientCompany: "Solis Botanicals",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
    quote: "Tushar's attention to detail on both digital and packaging design is extraordinary. Highly recommended for any brand seeking luxury elevation!",
    rating: 5,
  },
];
